name: Metrics

on:
  schedule:
    - cron: '0 * * * *'  # Runs at every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: repositories
          config_timezone: Europe/Paris
          plugin_calendar: yes
          plugin_calendar_days: 180
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: code
          plugin_languages_ignored: markdown, html
          plugin_languages_skipped: SVG, TeX
          plugin_music: yes
          plugin_music_token: ${{ secrets.SPOTIFY_CLIENT_ID }} ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Update metrics" || exit 0
          git push
